; Custom PHP configuration for Laravel development server
upload_tmp_dir = "D:/eSupportTechnologies/Booking-website/storage/tmp"
sys_temp_dir = "D:/eSupportTechnologies/Booking-website/storage/tmp"
upload_max_filesize = 10M
post_max_size = 12M
